### ISSUE TITLE
Browserify does not work with plugin Global Bind

### ISSUE THREAD

**Issue by silentkid86** [PolicyStat/combokeys#43]
I am working on a project that needs this feature by default on front end. However when i invoke the bindglobal function, it is throwing error for trying to override the stopCallback function. I have did another version to include this by default. 

Going further , you can check whether ctrl / alt / cmd is part of the combo then try to bind it global by default?

**Comment by mightyiam** [comment]
Thank you for your input, @silentkid86.

Can you provide a pull request where the plugin is fixed?

Can you explain why `ctrl`/`alt/`cmd` are to be globally bound by default?

**Comment by silentkid86** [comment]
combos with [ ctrl / alt / cmd + anykey ] should work even in text fields right? if the person typing in the text field, and he press [ ctrl / alt / cmd + somekey ] he intend to invoke certain function instead of typing anymore.

**Comment by mightyiam** [comment]
The story with text fields is that by default they do not trigger.

You can override that by replacing `Combokeys.stopCallback`.

Perhaps you were thinking that in order to override that you need `global-bind`?

**Comment by silentkid86** [comment]
oh, through the readme i thought the global bind is the only way. So I just call 'stopCallback' on the combokey object?

**Comment by mightyiam** [comment]
You replace `stopCallback`. See #7.
