### ISSUE TITLE
dom-event@^0.0.5 is unpublished and combokeys cannot be installed from NPM any more

### ISSUE THREAD

**Issue by huston007** [PolicyStat/combokeys#46]
```
> npm i combokeys
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/******/.nvm/versions/node/v5.7.1/bin/node" "/Users/******/.nvm/versions/node/v5.7.1/bin/npm" "i" "combokeys"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0

npm ERR! No compatible version found: dom-event@^0.0.5
npm ERR! Valid install targets:
npm ERR! 2.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/skladchikov/Documents/github/npm-debug.log
```

That's why it was unpublished https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.f4lrbinzn

**Comment by fasterthanlime** [comment]
note that the 2.0.0 install target npm talks about is a placeholder by npm squatter nj48: https://www.npmjs.com/~nj48 — I don't know at this time whether they have good or bad intentions.

**Comment by huston007** [comment]
I'd drop this package from dependencies and hardoce this two small functions inside combokeys to be independent ; )

**Comment by slangeberg** [comment]
Yes, please do merge this request. We just ran into same issue!
