### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by niksy** [PolicyStat/combokeys#48]
Since dependancy on `dom-event` was removed, it would be good to also push new version to npm.

**Comment by winhamwr** [comment]
Good call.

I just released v2.4.5 on github, and I've [asked](https://github.com/PolicyStat/combokeys/commit/8e75fa6deea961b68ed8a8a0819932901c34a795#commitcomment-16879409) @mightyiam for permission to collaborate on the NPM repo.

**Comment by mightyiam** [comment]
It seems that I did it (via the web UI).

**Comment by niksy** [comment]
https://www.npmjs.com/package/combokeys still says 2.4.4.

**Comment by winhamwr** [comment]
Thanks Shahar!

I just published v2.4.6 to npm. I accidentally burned the v2.4.5 tag first, because I forgot how npm works.

**Comment by magnudae** [comment]
Thank you @winhamwr!
