### ISSUE TITLE
'any-character' firing for cmd+c/ctrl+c on Firefox

### ISSUE THREAD

**Issue by TheSisb** [PolicyStat/combokeys#49]
Readme says 'any-character' only fires for "any character (actual character inserted—triggered by the `keypress` event" which works fine on Chrome, but breaks on Firefox.

**Comment by TheSisb** [comment]
Just handled it from my end with an `if (e.metaKey || e.ctrlKey)`

**Comment by caltonji** [comment]
How did you fix this? I stil have the issue
